# Generated by Django 5.0.7 on 2024-07-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img',
        ),
    ]
