# Generated by Django 5.0.7 on 2024-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_remove_recipe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='../images/default.jpg', upload_to='images'),
        ),
    ]
