# Generated by Django 5.0.7 on 2024-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0003_recipe_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img',
        ),
        migrations.AddField(
            model_name='recipe',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
